version: '3.8'

services: 
  sonic-server:
    image: valeriansaliou/sonic:v1.3.0
    container_name: sonic-server
    ports: 
      - '1491:1491'
    volumes: 
      - ./config.cfg:/etc/sonic.cfg
      - ./store/:/var/lib/sonic/store/
      